
    top_qsys u0 (
        .memory_mem_a                                                (<connected-to-memory_mem_a>),                                                //                            memory.mem_a
        .memory_mem_ba                                               (<connected-to-memory_mem_ba>),                                               //                                  .mem_ba
        .memory_mem_ck                                               (<connected-to-memory_mem_ck>),                                               //                                  .mem_ck
        .memory_mem_ck_n                                             (<connected-to-memory_mem_ck_n>),                                             //                                  .mem_ck_n
        .memory_mem_cke                                              (<connected-to-memory_mem_cke>),                                              //                                  .mem_cke
        .memory_mem_cs_n                                             (<connected-to-memory_mem_cs_n>),                                             //                                  .mem_cs_n
        .memory_mem_dm                                               (<connected-to-memory_mem_dm>),                                               //                                  .mem_dm
        .memory_mem_ras_n                                            (<connected-to-memory_mem_ras_n>),                                            //                                  .mem_ras_n
        .memory_mem_cas_n                                            (<connected-to-memory_mem_cas_n>),                                            //                                  .mem_cas_n
        .memory_mem_we_n                                             (<connected-to-memory_mem_we_n>),                                             //                                  .mem_we_n
        .memory_mem_reset_n                                          (<connected-to-memory_mem_reset_n>),                                          //                                  .mem_reset_n
        .memory_mem_dq                                               (<connected-to-memory_mem_dq>),                                               //                                  .mem_dq
        .memory_mem_dqs                                              (<connected-to-memory_mem_dqs>),                                              //                                  .mem_dqs
        .memory_mem_dqs_n                                            (<connected-to-memory_mem_dqs_n>),                                            //                                  .mem_dqs_n
        .memory_mem_odt                                              (<connected-to-memory_mem_odt>),                                              //                                  .mem_odt
        .oct_rzqin                                                   (<connected-to-oct_rzqin>),                                                   //                               oct.rzqin
        .mem_if_ddr3_emif_fpga_status_local_init_done                (<connected-to-mem_if_ddr3_emif_fpga_status_local_init_done>),                //      mem_if_ddr3_emif_fpga_status.local_init_done
        .mem_if_ddr3_emif_fpga_status_local_cal_success              (<connected-to-mem_if_ddr3_emif_fpga_status_local_cal_success>),              //                                  .local_cal_success
        .mem_if_ddr3_emif_fpga_status_local_cal_fail                 (<connected-to-mem_if_ddr3_emif_fpga_status_local_cal_fail>),                 //                                  .local_cal_fail
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_mem_clk               (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_mem_clk>),               // mem_if_ddr3_emif_fpga_pll_sharing.pll_mem_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_write_clk             (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_write_clk>),             //                                  .pll_write_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_locked                (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_locked>),                //                                  .pll_locked
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_write_clk_pre_phy_clk>), //                                  .pll_write_clk_pre_phy_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_addr_cmd_clk          (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_addr_cmd_clk>),          //                                  .pll_addr_cmd_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_avl_clk               (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_avl_clk>),               //                                  .pll_avl_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_config_clk            (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_config_clk>),            //                                  .pll_config_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_dr_clk                (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_dr_clk>),                //                                  .pll_dr_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_dr_clk_pre_phy_clk    (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_dr_clk_pre_phy_clk>),    //                                  .pll_dr_clk_pre_phy_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_mem_phy_clk           (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_mem_phy_clk>),           //                                  .pll_mem_phy_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_afi_phy_clk               (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_afi_phy_clk>),               //                                  .afi_phy_clk
        .mem_if_ddr3_emif_fpga_pll_sharing_pll_avl_phy_clk           (<connected-to-mem_if_ddr3_emif_fpga_pll_sharing_pll_avl_phy_clk>),           //                                  .pll_avl_phy_clk
        .hsp_memory_mem_a                                            (<connected-to-hsp_memory_mem_a>),                                            //                        hsp_memory.mem_a
        .hsp_memory_mem_ba                                           (<connected-to-hsp_memory_mem_ba>),                                           //                                  .mem_ba
        .hsp_memory_mem_ck                                           (<connected-to-hsp_memory_mem_ck>),                                           //                                  .mem_ck
        .hsp_memory_mem_ck_n                                         (<connected-to-hsp_memory_mem_ck_n>),                                         //                                  .mem_ck_n
        .hsp_memory_mem_cke                                          (<connected-to-hsp_memory_mem_cke>),                                          //                                  .mem_cke
        .hsp_memory_mem_cs_n                                         (<connected-to-hsp_memory_mem_cs_n>),                                         //                                  .mem_cs_n
        .hsp_memory_mem_ras_n                                        (<connected-to-hsp_memory_mem_ras_n>),                                        //                                  .mem_ras_n
        .hsp_memory_mem_cas_n                                        (<connected-to-hsp_memory_mem_cas_n>),                                        //                                  .mem_cas_n
        .hsp_memory_mem_we_n                                         (<connected-to-hsp_memory_mem_we_n>),                                         //                                  .mem_we_n
        .hsp_memory_mem_reset_n                                      (<connected-to-hsp_memory_mem_reset_n>),                                      //                                  .mem_reset_n
        .hsp_memory_mem_dq                                           (<connected-to-hsp_memory_mem_dq>),                                           //                                  .mem_dq
        .hsp_memory_mem_dqs                                          (<connected-to-hsp_memory_mem_dqs>),                                          //                                  .mem_dqs
        .hsp_memory_mem_dqs_n                                        (<connected-to-hsp_memory_mem_dqs_n>),                                        //                                  .mem_dqs_n
        .hsp_memory_mem_odt                                          (<connected-to-hsp_memory_mem_odt>),                                          //                                  .mem_odt
        .hsp_memory_mem_dm                                           (<connected-to-hsp_memory_mem_dm>),                                           //                                  .mem_dm
        .hsp_memory_oct_rzqin                                        (<connected-to-hsp_memory_oct_rzqin>),                                        //                                  .oct_rzqin
        .clk_clk                                                     (<connected-to-clk_clk>),                                                     //                               clk.clk
        .reset_reset_n                                               (<connected-to-reset_reset_n>),                                               //                             reset.reset_n
        .hps_0_h2f_reset_reset_n                                     (<connected-to-hps_0_h2f_reset_reset_n>),                                     //                   hps_0_h2f_reset.reset_n
        .top_no_ddr3_0_vga_r_export                                  (<connected-to-top_no_ddr3_0_vga_r_export>),                                  //               top_no_ddr3_0_vga_r.export
        .top_no_ddr3_0_vga_g_export                                  (<connected-to-top_no_ddr3_0_vga_g_export>),                                  //               top_no_ddr3_0_vga_g.export
        .top_no_ddr3_0_vga_b_export                                  (<connected-to-top_no_ddr3_0_vga_b_export>),                                  //               top_no_ddr3_0_vga_b.export
        .top_no_ddr3_0_vga_hs_export                                 (<connected-to-top_no_ddr3_0_vga_hs_export>),                                 //              top_no_ddr3_0_vga_hs.export
        .top_no_ddr3_0_vga_vs_export                                 (<connected-to-top_no_ddr3_0_vga_vs_export>),                                 //              top_no_ddr3_0_vga_vs.export
        .top_no_ddr3_0_vga_blank_n_export                            (<connected-to-top_no_ddr3_0_vga_blank_n_export>),                            //         top_no_ddr3_0_vga_blank_n.export
        .top_no_ddr3_0_vga_sync_n_export                             (<connected-to-top_no_ddr3_0_vga_sync_n_export>),                             //          top_no_ddr3_0_vga_sync_n.export
        .top_no_ddr3_0_vga_clk_export                                (<connected-to-top_no_ddr3_0_vga_clk_export>),                                //             top_no_ddr3_0_vga_clk.export
        .top_no_ddr3_0_test_pat_export                               (<connected-to-top_no_ddr3_0_test_pat_export>)                                //            top_no_ddr3_0_test_pat.export
    );

