output                        [14:0]               DDR3_A,
output                        [2:0]                DDR3_BA,
output                                             DDR3_CAS_n,
output                                             DDR3_CKE,
output                                             DDR3_CK_n,
output                                             DDR3_CK_p,
output                                             DDR3_CS_n,
output                        [3:0]                DDR3_DM,
inout                         [31:0]               DDR3_DQ,
inout                         [3:0]                DDR3_DQS_n,
inout                         [3:0]                DDR3_DQS_p,
output                                             DDR3_ODT,
output                                             DDR3_RAS_n,
output                                             DDR3_RESET_n,
input                                              DDR3_RZQ,
output                                             DDR3_WE_n,


fpga_ddr3 fpga_ddr3_inst(
  .pll_ref_clk           (OSC_50_B4A),       
  .global_reset_n        (test_global_reset_n),    
  .soft_reset_n          (test_software_reset_n),      
  .afi_clk               (afi_clk),           
  .afi_half_clk          (),      
  .afi_reset_n           (),       
  .mem_a                 (DDR3_A),             
  .mem_ba                (DDR3_BA),            
  .mem_ck                (DDR3_CK_p),            
  .mem_ck_n              (DDR3_CK_n),          
  .mem_cke               (DDR3_CKE),           
  .mem_cs_n              (DDR3_CS_n),          
  .mem_dm                (DDR3_DM),            
  .mem_ras_n             (DDR3_RAS_n),         
  .mem_cas_n             (DDR3_CAS_n),         
  .mem_we_n              (DDR3_WE_n),          
  .mem_reset_n           (DDR3_RESET_n),       
  .mem_dq                (DDR3_DQ),            
  .mem_dqs               (DDR3_DQS_p),           
  .mem_dqs_n             (DDR3_DQS_n),         
  .mem_odt               (DDR3_ODT),    

  .avl_ready             (fpga_ddr3_avl_ready),         
  .avl_burstbegin        (fpga_ddr3_avl_burstbegin),    
  .avl_addr              (fpga_ddr3_avl_addr),          
  .avl_rdata_valid       (fpga_ddr3_avl_rdata_valid),   
  .avl_rdata             (fpga_ddr3_avl_rdata),         
  .avl_wdata             (fpga_ddr3_avl_wdata),         
  .avl_be                (16'hFFFF),            
  .avl_read_req          (fpga_ddr3_avl_read_req),      
  .avl_write_req         (fpga_ddr3_avl_write_req),     
  .avl_size              (fpga_ddr3_avl_size),          
  .local_init_done       (fpga_ddr3_local_init_done),   
  .local_cal_success     (fpga_ddr3_local_cal_success), 
  .local_cal_fail        (fpga_ddr3_local_cal_fail),    

  .oct_rzqin             (DDR3_RZQ));


